# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Esther Adenuga | Computational Linguist
first_name: Esther
middle_name:
last_name: Adenuga
email: eadenuga004@stu.edu.ui.ng
description: Esther Adenuga | NLP Research Fellow | African Research Collective
footer_text: Powered by Jekyll with al-folio theme.

icon: ⚆
url: "https://adeleyi.github.io"   # base hostname & protocol
baseurl: ""                        # keep empty for user site (adeleyi.github.io)
last_updated: true
impressum_path:

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
max_width: 800px

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------

serve_og_meta: false
og_image:

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: adeleyi
twitter_username: theadeleyi
linkedin_username: esther-adenuga-
#scholar_userid:
#semantic_scholar_userid:
orcid_id:
medium_username:
quora_username:
publons_id:
research_gate_profile:
blogger_url:
keybase_username:
wikidata_id:
dblp_url:

contact_note: >

google_analytics: UA-XXXXXXXXX
panelbear_analytics: XXXXXXXXX

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: CV
blog_description:
permalink: /CV/

pagination:
  enabled: true

disqus_shortname: al-folio

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_scrollable: false
news_limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
highlight_theme: github
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

plugins:
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-twitter-plugin
  - jekyll-sitemap
  - jemoji

github: [metadata]

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: Adenuga
  first_name: [Esther]

  style: apa
  locale: en
  source: /_bibliography/
  bibliography: [papers.bib, patents.bib]
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    true
enable_panelbear_analytics: false
enable_mansory:             true
enable_math:                true
enable_tooltips:            false
enable_darkmode:            false
enable_navbar_social:       false
enable_project_categories:  true
enable_medium_zoom:         true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.0"
  integrity: "sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg=="
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.2.0"
mansory:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
medium_zoom:
  version: "1.0.6"
  integrity: "sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM="
